[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyfetch-izak"
version = "0.1.0"
description = "A minimal fastfetch-style system info tool written in Python"
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }
authors = [
    { name = "izak" }
]
dependencies = [
    "psutil>=5.9.0"
]

[project.scripts]
pyfetch = "pyfetch.main:main"

[tool.setuptools.packages.find]
where = ["src"]
